version: '3.8'

services:
  # Base de données PostgreSQL
  db:
    image: postgres:13
    container_name: palmares_db
    environment:
      POSTGRES_DB: palmares_imara
      POSTGRES_USER: palmares_user
      POSTGRES_PASSWORD: palmares_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    networks:
      - palmares_network
    restart: unless-stopped

  # Redis pour le cache (optionnel)
  redis:
    image: redis:7-alpine
    container_name: palmares_redis
    ports:
      - "6379:6379"
    networks:
      - palmares_network
    restart: unless-stopped

  # Application Django
  web:
    build: .
    container_name: palmares_web
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-in-production}
      - DATABASE_URL=postgresql://palmares_user:palmares_password@db:5432/palmares_imara
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-admin123}
    volumes:
      - media_files:/app/media
      - static_files:/app/staticfiles
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - palmares_network
    restart: unless-stopped

  # Nginx pour servir les fichiers statiques (production)
  nginx:
    image: nginx:alpine
    container_name: palmares_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - static_files:/var/www/static
      - media_files:/var/www/media
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - palmares_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  media_files:
    driver: local
  static_files:
    driver: local

networks:
  palmares_network:
    driver: bridge
